/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAvaliacaoRouteImport } from './routes/dashboard.avaliacao'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardProntuariosRouteImport } from './routes/dashboard.prontuarios'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as DashboardClientesPatientIdRouteImport } from './routes/dashboard.clientes.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvaliacaoRoute = DashboardAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProntuariosRoute = DashboardProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientesPatientIdRoute =
  DashboardClientesPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => DashboardClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/prontuarios': typeof DashboardProntuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/clientes/$patientId': typeof DashboardClientesPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/prontuarios': typeof DashboardProntuariosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/clientes/$patientId': typeof DashboardClientesPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/avaliacao': typeof DashboardAvaliacaoRoute
  '/dashboard/clientes': typeof DashboardClientesRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/prontuarios': typeof DashboardProntuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/dashboard/clientes/$patientId': typeof DashboardClientesPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/trocar-senha'
    | '/dashboard/agenda'
    | '/dashboard/avaliacao'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/prontuarios'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/clientes/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/trocar-senha'
    | '/dashboard/agenda'
    | '/dashboard/avaliacao'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/prontuarios'
    | '/dashboard'
    | '/auth/google/callback'
    | '/dashboard/clientes/$patientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/trocar-senha'
    | '/dashboard/agenda'
    | '/dashboard/avaliacao'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/prontuarios'
    | '/dashboard/'
    | '/auth/google/callback'
    | '/dashboard/clientes/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/avaliacao': {
      id: '/dashboard/avaliacao'
      path: '/avaliacao'
      fullPath: '/dashboard/avaliacao'
      preLoaderRoute: typeof DashboardAvaliacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prontuarios': {
      id: '/dashboard/prontuarios'
      path: '/prontuarios'
      fullPath: '/dashboard/prontuarios'
      preLoaderRoute: typeof DashboardProntuariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clientes/$patientId': {
      id: '/dashboard/clientes/$patientId'
      path: '/$patientId'
      fullPath: '/dashboard/clientes/$patientId'
      preLoaderRoute: typeof DashboardClientesPatientIdRouteImport
      parentRoute: typeof DashboardClientesRoute
    }
  }
}

interface DashboardClientesRouteChildren {
  DashboardClientesPatientIdRoute: typeof DashboardClientesPatientIdRoute
}

const DashboardClientesRouteChildren: DashboardClientesRouteChildren = {
  DashboardClientesPatientIdRoute: DashboardClientesPatientIdRoute,
}

const DashboardClientesRouteWithChildren =
  DashboardClientesRoute._addFileChildren(DashboardClientesRouteChildren)

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAvaliacaoRoute: typeof DashboardAvaliacaoRoute
  DashboardClientesRoute: typeof DashboardClientesRouteWithChildren
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardProntuariosRoute: typeof DashboardProntuariosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAvaliacaoRoute: DashboardAvaliacaoRoute,
  DashboardClientesRoute: DashboardClientesRouteWithChildren,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardProntuariosRoute: DashboardProntuariosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
